[package]
name = "grid-meter-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.0", features = ["rt", "sync", "macros", "time"] }
tokio-modbus = { version = "0.17.0", default-features = false, features = ["tcp-server"] }
